# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sevents-provisioner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sevents-provisioner
  template:
    metadata:
      labels:
        app: k8sevents-provisioner
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: controller
        image: github.com/knative/source-k8sevents/cmd/provisioner
        volumeMounts:
        - name: templates
          mountPath: /templates
      volumes:
      - name: templates
        configMap:
          name: k8sevents-source-templates
